//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "im_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: Option<i64>,
    pub name: Option<String>,
    pub avatar: Option<String>,
    pub email: String,
    pub account: String,
    pub sex: Option<i32>,
    pub open_id: String,
    pub active_status: Option<i32>,
    pub user_state_id: Option<i64>,
    pub last_opt_time: Option<DateTime>,
    pub ip_info: Option<Json>,  
    pub item_id: Option<i64>,
    pub state: Option<i32>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub password: String,
    pub avatar_update_time: Option<DateTime>,
    pub num: i32,
    pub context: bool,
    pub user_type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
