//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "im_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: String,
    pub user_id: Option<i64>,
    pub name: Option<String>,
    pub avatar: Option<String>,
    pub email: Option<String>,
    pub account: Option<String>,
    pub sex: Option<i32>,
    pub open_id: Option<String>,
    pub active_status: Option<i32>,
    pub user_state_id: Option<i64>,
    pub last_opt_time: Option<i64>,
    pub ip_info: Option<Json>,
    pub item_id: Option<i64>,
    pub state: Option<i32>,
    pub create_time: Option<i64>,
    pub update_time: Option<i64>,
    pub password: Option<String>,
    pub avatar_update_time: Option<i64>,
    pub num: Option<i32>,
    pub context: Option<bool>,
    pub user_type: Option<i32>,
    pub is_init: bool,
    pub token: Option<String>,
    pub refresh_token: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
