database:
  sqlite_file: db.sqlite
backend:
  base_url: https://hulaspark.com/api
  ws_url: wss://hulaspark.com/api/ws/ws

youdao:
  app_key: ''
  app_secret: ''
tencent:
  api_key: ''
  secret_id: ''
